batch_size: 6
devices: '2'
epochs: 50
experiment_name: baseline_1B_explr
max_length: 450
optimizer:
  lr: 6.0e-05
  scheduler_kwargs:
    gamma: 0.95
  scheduler_type: exponential
  weight_decay: 0.01
param_count: 1.3B
