experiment_name: curriculum_125M_first
param_count: 125M
devices: "0"
epochs: 50
max_length: 450 
batch_size: 16
optimizer: 
    lr: 6.0e-5
    weight_decay: 0.01
    scheduler_type: exponential 
    scheduler_kwargs: 
        gamma: 0.95
curriculum: 
    scoring_function: CodeLength
    start_props:
        - 0.1
        - 0.2
    step_lengths: 
        - 6005
        - 12010
    increase: 
        - 1.5
