experiment_name: baseline_125M_dev_explr_vesna
param_count: 125M
devices: "0"
epochs: 50
max_length: 450 
batch_size: 32
optimizer: 
    lr: 6.0e-5
    weight_decay: 0.01
    scheduler_type: exponential 
    scheduler_kwargs: 
        gamma: 0.95
