experiment_name: baseline_1B_explr
param_count: 1.3B
devices: "2"
epochs: 50
max_length: 450 
batch_size: 6
optimizer: 
    lr: 6.0e-5
    weight_decay: 0.01
    scheduler_type: exponential 
    scheduler_kwargs: 
        gamma: 0.95
