batch_size: 3
devices: null
epochs: 50
experiment_name: baseline_2B_explr
max_length: 450
optimizer:
  lr: 6.0e-05
  scheduler_kwargs:
    gamma: 0.95
  scheduler_type: exponential
  weight_decay: 0.01
param_count: 2.7B
